#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time

if __name__ == "__main__":
    # python >= 3.7
    time_ns = getattr(time, "time_ns", None)
    if time_ns:
        print(time_ns())
    else:
        print(int(time.time() * 1e9))
